var engRelationsGraph = {
  "your" : {
    "father" : "father",
    "mother" : "mother",
    "husband" : "husband",
    "wife": "wife",
    "son": "son",
    "daughter" : "daughter",
  }, 
  "mother" : {
    "father" : "grandfather",
    "mother" : "grandmother",
    "husband" : "father",
    "wife": "mother",
    "son": "son",
    "daughter" : "daughter",
  }, 
  "father" : {
    "father" : "grandfather",
    "mother" : "grandmother",
    "husband" : "father",
    "wife": "mother",
    "son": "son",
    "daughter" : "daughter",
  }, 
  "grandfather" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "grandmother" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "uncle" : {
    "father" : "grandfather",
    "mother" : "grandmother",
    "husband" : "uncle",
    "wife": "aunt",
    "son": "cousin",
    "daughter" : "cousin",
  }, 
  "aunt" : {
    "father" : "grandfather",
    "mother" : "grandmother",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "cousin" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "sister" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "brother" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "sibling_son" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "sibling_daughter" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "husband" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "wife" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "sister_in_law" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "brother_in_law" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "son" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "daughter" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "child_son" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "child_wife" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "granddaughter" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "grandson" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "spouse_mother" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
  "spouse_father" : {
    "father" : "",
    "mother" : "",
    "husband" : "",
    "wife": "",
    "son": "",
    "daughter" : "",
  }, 
}

var def = {
  "your" : "you", 
  "mother" : "mom", 
  "father" : "dad", 
  "grandfather" : "grandpa", 
  "grandmother" : "grandma", 
  "uncle" : "uncle", 
  "aunt" : "aunt", 
  "cousin" : "cousin", 
  "sister" : "sister", 
  "brother" : "brother",
  "sibling_son" : "nephew", 
  "sibling_daughter" : "niece",
  "husband" : "husband", 
  "wife" : "wife", 
  "sister_in_law" : "sister-in-law",
  "brother_in_law" : "brother-in-law",
  "son" : "son", 
  "daughter" : "daughter", 
  "child_son" : "son-in-law", 
  "child_wife" : "daughter-in-law", 
  "granddaughter" : "granddaughter", 
  "grandson" : "grandson", 
  "spouse_mother" : "mother-in-law", 
  "spouse_father" : "father-in-law", 
}